version: "3"

services:
    db:
      container_name: postgres
      image: postgres
      environment:
        POSTGRES_HOST: postgres
        POSTGRES_PASSWORD: 123456
        POSTGRES_USERNAME: postgres
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
    product-service:
      image: ivanspasov/springbootapi:latest
      ports:
        # how now to expose back end api, axios??
        - 9000:9000
      depends_on:
        - db
    fron-end-service:
      image: ivanspasov/vue-js-front-end:latest
      ports:
      - 8080:80
      depends_on:
        - product-service